config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'
  get 'pages/about'


  resources :proposals do
    resources :histories
  end



  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :proposal
  belongs_to :user
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  has_many :histories, dependent: :destroy

  validates :name, presence: true,
                    length: { minimum: 5 }
  validates :email, presence: true,
                    length: { minimum: 7 }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
    message: " must be valid" }                    
 
  validates :state, presence: true,
                    length: { minimum: 2 }                             
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :histories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :password, :email, :password_confirmation])
        devise_parameter_sanitizer.permit(:user_update, keys: [:user_name, :password, :email])
      end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
   def create
    @proposal = Proposal.find(params[:proposal_id])
    @history = @proposal.histories.create(history_params)
    @history.user_id = current_user.id
    if @history.save
      redirect_to proposal_path(@history.proposal_id)
    else
      flash.now[:danger] = "History was not correctly saved!"
    end
  end
 
 def destroy
    @proposal = Proposal.find(params[:proposal_id])
    @history = @proposal.histories.find(params[:id])
    @history.destroy
    redirect_to proposal_path(@proposal)
  end

  private
    def history_params
      params.require(:history).permit(:note, :contacted)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
    before_action :require_login, except: [:new, :create]
 


  def index
    @proposals = Proposal.order(created_at: :desc)
  end

  def new
    @proposal = Proposal.new
  end

  def edit
    @proposal = Proposal.find(params[:id])
  end

  def create
    @proposal = Proposal.new(proposal_params)
    if @proposal.valid?
      @proposal.save!
      redirect_to '/'
    else
      render 'errors'
    end
  end

  def update
    @proposal = Proposal.find(params[:id])
   
    if @proposal.update(proposal_params)
      redirect_to @proposal
    else
      render 'edit'
    end
  end

  def show
   @proposal = Proposal.find(params[:id])
  end


  def destroy
    @proposal = Proposal.find(params[:id])
    @proposal.destroy
   
    redirect_to proposals_path
  end

  private

  def require_login
    unless user_signed_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to new_user_session_path # halts request cycle
    end
  end

  def proposal_params
    params.require(:proposal).permit(:name, :email, :company, :website_url, :phone, :email, :address, :city, :state, :zip, :website_goals)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end 

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/histories/_form.html.erb
<%= form_for([@proposal, @proposal.histories.build]) do |f| %>
  <p>
    Was the customer contacted about this? <br>
    <%= f.label :contacted, "Yes", :value => "true"  %>
    <%= f.radio_button :contacted, true, :checked => false %>
    <%= f.label :contacted, "No", :value => "false" %>
    <%= f.radio_button :contacted, false, :checked => true %>
    <!-- <input id="contacted" name="contacted" type="checkbox" value="1" />
    <label for="contacted">I talked to the customer about this</label> -->
    <%#= check_box_tag(:contacted) %>
    <%#= label_tag(:contacted, "I talked to the customer about this") %>
  </p>

  <p>
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/histories/_history.html.erb
<p>
  
  <% if @proposal.histories.count != 0 %>
    <%= history.created_at.to_s.slice!(0..9) %>
    <%= history.contacted %>
      <% if history.user.nil? %>
      <% else %>
        <%= history.user.user_name %>
        <strong>Note: </strong>
        <%= history.note %>

        <%= link_to 'Destroy History', [history.proposal, history],
                     method: :delete,
                     data: { confirm: 'Are you sure?' } %>
      <% end %>
  <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BigMouthFrogWebMk2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
  <%= render "shared/nav" %>
        

<div class="row">
          <div class="col s4">  
            <div class="card">
          <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="https://vignette2.wikia.nocookie.net/pikmin/images/4/4f/Lily_pad_stock_2_by_moonchilde_stock-d3g50nk.jpg/revision/latest?cb=20130804155443">
          </div>
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4">Card Title<i class="material-icons right">more_vert</i></span>
            <p><a href="#">This is a link</a></p>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
            <p>Here is some more information about this product that is only revealed once clicked on.</p>
          </div>
        </div>
    </div>
        <div class="col s8">
          <div class="card">
            <div class="card-image">
              <img src="https://upload.wikimedia.org/wikipedia/commons/5/55/Atelopus_zeteki1.jpg">
              <span class="card-title">Card Title</span>
            </div>
            <div class="card-content">
              <p>I am a very simple card. I am good at containing small bits of information.
              I am convenient because I require little markup to use effectively.</p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
            </div>
          </div>
        </div>
      </div>









  <div class="fixed-action-btn">
    <a class="btn-floating btn-large red">
      <i class="large material-icons">mode_edit</i>
    </a>
    <ul>
      <li><a class="btn-floating red"><i class="material-icons">insert_chart</i></a></li>
      <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
      <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
    </ul>
  </div>
        

app/views/proposals/_form.html.erb
<%= form_for :proposal, url: proposals_path do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </p>

    <p>
    <%= f.label :company %><br>
    <%= f.text_area :company %>
  </p>
    <p>
    <%= f.label :website_url %><br>
    <%= f.text_area :website_url %>
  </p>
    <p>
    <%= f.label :phone %><br>
    <%= f.text_area :phone %>
  </p>
    <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>
    <p>
    <%= f.label :city %><br>
    <%= f.text_area :city %>
  </p>
    <p>
    <%= f.label :state %><br>
    <%= f.text_area :state %>
  </p>
    <p>
    <%= f.label :zip %><br>
    <%= f.text_area :zip %>
  </p>

    <p>
    <%= f.label :website_goals %><br>
    <%= f.text_area :website_goals %>
  </p>
        
  <p>
    <%= f.button "Submit", class: "btn", data: {disable_with: "<i class='fa fa-spinner fa-spin' aria-hidden='true'></i> Submitting"} %>
  </p>
<% end %>

app/views/proposals/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>

app/views/proposals/errors.html.erb
  <% if @proposal.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@proposal.errors.count, "error") %> prohibited
        this proposal from being saved:
      </h2>
      <ul>
        <% @proposal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/proposals/index.html.erb
<h1>Listing articles</h1>
 

      <table>
        <thead>
          <tr>
              <th>Name</th>
              <th>Company</th>
              <th>Website Url</th>
              <th>Phone</th>
              <th>Email</th>
              <th>Address</th>
              <th>City/State/Zip</th>
              <th>Goals</th>
          </tr>
        </thead>

        <tbody>
            
        <% @proposals.each do |proposal| %>
          <tr>
            <td><%= link_to proposal.name, proposal_path(proposal) %></td>
            <td><%= proposal.company %></td>
            <td><%= proposal.website_url %></td>
            <td><%= proposal.phone %></td>
            <td><%= proposal.email %></td>
            <td><%= proposal.address %></td>
            <td><%= proposal.city %><%= proposal.state %><%= proposal.zip %></td>
            <td><%= proposal.website_goals %></td>
            <td><%= link_to 'Edit', edit_proposal_path(proposal) %></td>
            <td><%= link_to 'Destroy', proposal_path(proposal),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

app/views/proposals/new.html.erb
<h1>New Proposal</h1>
<%= render 'form' %>

app/views/proposals/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @proposal.name %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @proposal.email %>
</p>

<p>
  <strong>Company:</strong>
  <%= @proposal.company %>
</p>

<p>
  <strong>Website Url:</strong>
  <%= @proposal.website_url %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @proposal.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @proposal.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @proposal.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @proposal.state %>
</p>

<p>
  <strong>Zip Code:</strong>
  <%= @proposal.zip %>
</p>
<p>
  <strong>Website Goals:</strong>
  <%= @proposal.website_goals %>
</p>

<h2>Add a History:</h2>
<%= render 'histories/form' %>

<h2>History</h2>
<%= render @proposal.histories %>

<%= link_to 'Edit', edit_proposal_path(@proposal) %> |
<%= link_to 'Back', proposals_path %>

app/views/shared/_nav.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li>
    <% if user_signed_in? %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %> 
      <a href="/users/sign_in">Login</a>
  <li class="divider"></li>
      <a href="/users/sign_up" style="color: green">Sign-Up</a>
  </li>
    <% end %>

</ul>
<nav>
  <div class="nav-wrapper" style="position: top;">
    <a href="#!" class="brand-logo">Logo</a>
    <ul class="right hide-on-med-and-down" style="max-height: 5em;">
      <li><a class="circle pulse"><img class="circle pulse" width="65" src="/Users/nygard/Desktop/froglogoside"></a></li>
      <li><a href="/proposals/new">Request a Quote</a></li>
      <li><a href="/pages/about">About Us</a></li>
        <% if user_signed_in? %>
          <li><a href="/proposals">Proposals</a></li>
        <% end %>
      <!-- Dropdown Trigger -->
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>